// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  articles_list: dynamic(() => import("./ArticlesList")),
  form: dynamic(() => import("./Form")),
  hero: dynamic(() => import("./Hero")),
  text_slice: dynamic(() => import("./TextSlice")),
};
